#include "../list/list.h"
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
//issue: no string struct
//so many casts from int to int64(is indexing can work with int64? check)
typedef struct Bucket{
List* Collisions;
}Bucket;
typedef struct HashMap{
   Bucket* Buckets;
   int len;
   int64_t PrimeNumber; //seed
}HashMap;
int64_t HashGenerator(const char* str,int64_t primeNumber){
    int64_t result=0;
    for (size_t i=0;str[i]!='\0';i++){
        result=result*primeNumber;
        result^=str[i];
    }
    return result;
}
//NOTICE PRIME NUMBER NOT GENERATED BY PROGRAM USED AS CONST. ADD REALISATION.
HashMap* CreateHashMap(int len){
    HashMap* table=(HashMap*)malloc(sizeof(HashMap));
    table->len=len;
    table->Buckets=(Bucket*)malloc(len*sizeof(Bucket));
    table->PrimeNumber=813951179412191; //from random prime number generator, better idea generate always i think
    return table;
}
//O(1)
void Add(HashMap* table,const char* key, int val){
    int64_t index=HashGenerator(key,table->PrimeNumber);
    int trueIndex=(int)(index%(int64_t)table->len);
    table->Buckets[trueIndex].Collisions=CreateList(val);
}
//0 - false 1 - true  O(1)
int Lookup(HashMap* table,const char* key){
    int64_t index=HashGenerator(key,table->PrimeNumber);
    int trueIndex=(int)(index%(int64_t)table->len);
    if (table->Buckets[trueIndex].Collisions!=NULL){
        return 1;
    }else {return 0;}
}
//O(1) NOTICE: THIS IS RAW IMPLEMENTATION DOESNT RETURN ALL LIST OF COLLISIONS.
int Get(HashMap* table,const char* key){
    int64_t index=HashGenerator(key,table->PrimeNumber);
    int trueIndex=(int)(index%(int64_t)table->len);
    if (table->Buckets[trueIndex].Collisions!=NULL){
        return table->Buckets[trueIndex].Collisions->Val;
    }else {return 0;}
}
//O(1)
void Delete(HashMap* table,const char* key){
    int64_t index=HashGenerator(key,table->PrimeNumber);
    int trueIndex=(int)(index%(int64_t)table->len);
    if (table->Buckets[trueIndex].Collisions!=NULL){
        FreeList(table->Buckets[trueIndex].Collisions);
    }else {return;}
}

void PurgeHashMap(HashMap* table){
    for (int i=0;i<table->len;i++){
        if (table->Buckets[i].Collisions!=NULL){
            FreeList(table->Buckets[i].Collisions);
        }
    }
    //is free clear all block of allocated memory by pointer?
    free(table->Buckets);
    free(table);
    
}


